var words = [
	["la nourriture","food, nutrition"],
	["boissons","beverage"],
	["céréales","cereals"],
	["poisson","fish"],
	["viande","meat"],
	["féculants","carbohydrates"],
	["protéines","proteins"],
	["produits latiers","milk products"],
	["produits grasse","fatty products"],
	["produits sucré","sugary products"],
	["légumes","vegetables"],
	["thé","tea (m)"],
	["café","coffee"],
	["vin","wine"],
	["boissons sucré","sweetened drinks (coke, sprite...)"],
	["l'eau","water (f)"],
	["limonade","lemon soda"],
	["jus de fruit","fruit juice"],
	["jus de légumes","vegetable juice"],
	["chocolat chaud","hot chocolate"],
	["froide","cold chocolate"],
	["pâte","pasta (f)"],
	["fruits de la mer","seafood"],
	["poulet","chicken"],
	["porc","pork"],
	["jambon","bacon"],
	["lentilles","lentils"],
	["avoine","oats, oatmeal"],
	["le fromage","cheese"],
	["lait","milk"],
	["yaourt","yogurt"],
	["beurre","butter"],
	["l'huile d'olive","olive oil"],
	["bonbons","candies, sweets"],
	["gâteau","cake"],
	["la pomme","apple"],
	["l'ananas","pineapple"],
	["l'orange","orange"],
	["la banane","banana"],
	["carottes","carrots"],
	["épinards","spinach"],
	["petit pois","green peas"],
	["haricot vert","green beans"],
	["crevette","shrimps"],
	["saumon","salmon (a type of fish)"],
	["thon","tuna ( a type of fish)"],
	["santé","health"],
	["sain(e)","healthy"],
	["nouilles","noodles"],
	["ajouter","to add ( eg I add milk to my cereal)"],
	["alimentation saine","healthy food"],
	["équilibré","balanced"],
	["efficace","efficient"],
	["protéger","to protect"],
	["jus qu'à","up to/ untill"],
	["maladies","sickness"],
	["coeur","heart"],
	["prévenir","to prevent"],
	["grâce à","thanks to (positive)"],
	["vie","life"],
	["variété","variety"],
	["privilégier","to favour, to give priority to"],
	["comporter /inclure","to include"],
	["maintenir","to maintain"],
	["poids","weight"],
	["notamment","especially/particularly"],
	["les craquelins","crackers (m)"],
	["le riz","rice"],
	["le quinoa","quinoa"],
	["l'avoine","oats"],
	["il s'agit de","it's about"],
	["fruits de mer","seafood"],
	["des oeufs brouillés","scrambled eggs"],
	["volaille","poultry"],
	["le gibier","game (animals)"],
	["os","bones"],
	["la peau","skin"],
	["essayer","to try"],
	["au moins","at least (number, quantity)"],
	["composer","consists of"],
	["le quart","quarter"],
	["état","state, condition"],
	["ingrédiants","ingrediants"],
	["surgeléer","frozen food"],
	["emballer","to wrap up/packaged food"],
	["sèche","dry"],
	["hydrté","to hydrate"],
	["valeur","value, worth"],
	["recette","recipe (f)"],
	["couleurs vives","vibrant colors"],
	["Substitut","substitute"],
	["éviter","to avoid doing"],
	["sucre","sugar"],
	["sucré","sweet"],
	["conserver","to keep/ to preserve"],
	["réutilisable","to reuse"],
	["anfin de","in order to"],
	["remplir","to fill"],
	["partout","everywhere, all over"],
	["collations","snacks"],
	["malbouffe","junk food"],
	["un saladier","salad bowl"],
	["un fouet (à main)","whisk"],
	["une louche","ladle"],
	["une poêle à frire","frying pan, skillet"],
	["verser","pour"],
	["ajouter","to add to"],
	["mélanger","to mix"],
	["laisser reposer","to let sit"],
	["environ","approximately"],
	["étaler","to spread"],
	["cuire","to cook"],
	["chauffer","to heat up"],
	["oeufs au plat","fried eggs"],
	["oeufs brouillés","scrambled eggs"],
	["oeufs a la coque","boiled eggs"],
	["l'assaisonnement.","seasoning"],
	["haché","chopped / minced"],
	["surgelés","frozen food"],
	["sirop d'érable","maple syrup"],
	["bouillon","broth"],
	["une ville","city, town"],
	["un appartement","apartment"],
	["encombré","busy, crowded"],
	["le voisinage","the neighborhood"],
	["le parking","parking lot"],
	["le fontaine","water fountain"],
	["l'imeuble","apartment building"],
	["manifestation (f)","demonstration"],
	["gratte ciel","skyscraper"],
	["haut-parleur","loud speaker"],
	["foule","crowd, mob"],
	["étage","floor"],
	["l'opéra","opera house"],
	["la boite de nuit","night club"],
	["le piste cyclable","cycle lane"],
	["le vélo","cycling, bike"],
	["la verdure","greenery"],
	["casque","helmet"],
	["aéroport","airport"],
	["passe-port m","passport"],
	["valise","suitcase"],
	["sécurité","safety; security"],
	["majesteuse","majestic"],
	["billets","tickets"],
	["le bateau","boat"],
	["l'avoin","plane"],
	["l'autobus (m)","bus"],
	["le metro","underground"],
	["la voiture","car"],
	["je me déplace à pied","I go by foot."],
	["facile","easy"],
	["moyens de transport publique","public transport"],
	["prendre","to take"],
	["(assez) loin","(quite) a long way"],
	["tout près","very close"],
	["travailler","to work"],
	["meilleur ami","best friend"],
	["chez lui/elle","his/her house"],
	["à pied","by foot"],
	["la circulation","traffic"],
	["dense, imperméable","thick"],
	["seulement","only"],
	["quelquefois","sometimes"],
	["les plages","beaches"],
	["paques","easter"],
	["arrêter","to stop"],
	["spontanément","spontaneously"],
	["rencontrer","to meet"],
	["perdre","to lose"],
	["observer la paysage","observe the landscape"],
	["voyager pas cher","to travel cheap"],
	["emmener","to bring"],
	["se lever","to get up"],
	["se coucher","to go to bed"],
	["dépenser de l'argent","to spend (money)"],
	["apprendre","to learn"],
	["langues etrangères","foreign languages"],
	["etre seul","to be alone"],
	["être bloqué dans un embouteillage","get stuck in a traffic jam"],
	["vivre une aventure","to live an adventure"],
	["entendre","to hear"],
	["sentir bon","to feel good"],
	["mauvais","to feel bad"],
	["par là","over there"],
	["au bout du couloir","at the end of the corridor"],
	["juste là","right there"],
	["à côté de","next to, beside"],
	["en bas","downstairs"],
	["en haut","upstairs"],
	["au fond","towards the back"],
	["au rez-de-chaussée","ground floor"],
	["au premier étage","first floor"],
	["en face de","across from / facing"],
	["à l'entrée de","at the entrance of"],
	["à gauche de","to the left of"],
	["à droite","to the right of"],
	["tout droit","straight ahead"],
	["en bas de","at the bottom of"],
	["là-bas","over there (pointing)"],
	["ici","right here"],
	["à côté de","next to, beside"],
	["devant","in front of"],
	["derrière","behind, in back of"],
	["en dessous de","below / underneath"],
	["près de","near to"],
	["proche de","close to"],
	["loin de","far from"],
	["à l'est","east"],
	["à l'ouest","west"],
	["à nord","north"],
	["à sud de","to the south of"],
	["en plein campagne","in the middle of the countryside"],
	["faire les courses","to go grocery shopping"],
	["acheter","to buy"],
	["le journal","newspaper"],
	["voir","to see"],
	["centres commerciaux","shopping centers"],
	["tranquille","calm; quiet"],
	["sympas","nice, kind"],
	["peu de circulation","very little traffic"],
	["se détendre","to relax, to unwind"],
	["promenade","to walk"],
	["l'esprit communautaire","community spirit"],
	["connaître","to know, to be familiar with"],
	["voisin","neighbor"],
	["s'entreaider","to help each other"],
	["boulanger","baker"],
	["boucherie","butcher shop"],
	["épicier","grocer"],
	["à côté de","next to, beside"],
	["emprunter","to borrow"],
	["nager","to swim"],
	["piscine","swimming pool"],
	["centre de loisirs","recreation center"],
	["piste","track"],
	["paysage","landscape"],
	["alentours","surrounding area"],
	["verdure (f)","greenery"],
	["endroits","places, locations"],
	["faire des promenades","to go for walks"],
	["randonnées et balades à vélo","hikes, and bike rides"]
	];